# Generated by Django 4.2.4 on 2023-11-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productimage', models.ImageField(upload_to='')),
                ('productdesc', models.CharField(max_length=400)),
            ],
        ),
    ]
