# Generated by Django 4.2.4 on 2023-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_products_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserEmail', models.CharField(max_length=120)),
                ('usermobile', models.CharField(max_length=12)),
                ('userpassword', models.CharField(max_length=180)),
            ],
        ),
    ]
