# Generated by Django 4.2.4 on 2023-11-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_useremail_users_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtoken', models.CharField(max_length=20000)),
            ],
        ),
    ]
