# Generated by Django 4.2.4 on 2023-11-30 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
