# Generated by Django 4.2.4 on 2023-11-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tokens_email_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
