# Generated by Django 4.2.4 on 2023-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cart_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='media/userProfiles/default.png', upload_to='media/userProfiles'),
        ),
    ]
